### ISSUE TITLE
Exception attempting to detect unicode

### ISSUE THREAD

**Issue by reinholdsson** [blue-yonder/sqlalchemy_exasol#43]
I've an issue with unicode sending queries to Exasol. Running the following on Mac OS:

```
#!/usr/bin/python
# -*- coding: <utf-8> -*-
import sqlalchemy
from sqlalchemy import create_engine
e = create_engine('exa+pyodbc://EXA_TEST')

r = e.execute("select 3")
for row in r:
  print row
```

Result in:

```
/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py:298: SAWarning: Exception attempting to detect unicode returns: ProgrammingError('(pyodbc.ProgrammingError) (\'42000\', "[42000] [EXASOL][EXASolution driver]syntax error, unexpected end_of_input, expecting assignment_operator or \':\' [line 1, column 1] (Session: 1526508375593279549) (-1) (SQLExecDirectW)")',)
  "detect unicode returns: %r" % de)
Traceback (most recent call last):
  File "sqlalchemy_example.py", line 15, in <module>
    r = e.execute("select 3")
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1990, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/pool.py", line 454, in __init__
    exec_once(self.connection, self)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 246, in exec_once
    self(*args, **kw)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 1319, in go
    return once_fn(*arg, **kw)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 165, in first_connect
    dialect.initialize(c)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/connectors/pyodbc.py", line 154, in initialize
    super(PyODBCConnector, self).initialize(connection)
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 256, in initialize
    self._check_unicode_description(connection):
  File "/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 343, in _check_unicode_description
    ]).compile(dialect=self)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [EXASOL][EXASolution driver]syntax error, unexpected end_of_input, expecting assignment_operator or ':' [line 1, column 1] (Session: 1526508375593279549) (-1) (SQLExecDirectW)")
```

However, it does work the next time I run `execute`, e.g.:

```
#!/usr/bin/python
# -*- coding: <utf-8> -*-
import sqlalchemy
from sqlalchemy import create_engine
e = create_engine('exa+pyodbc://EXA_TEST')

# Temporary fix to unicode problem, works after running query the first time
# todo: investigate further into this
try:
    e.execute("select 1")
except sqlalchemy.exc.ProgrammingError:
    pass
###

r = e.execute("select 3")
for row in r:
  print row
```

=>

```
/Users/myusername/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py:298: SAWarning: Exception attempting to detect unicode returns: ProgrammingError('(pyodbc.ProgrammingError) (\'42000\', "[42000] [EXASOL][EXASolution driver]syntax error, unexpected end_of_input, expecting assignment_operator or \':\' [line 1, column 1] (Session: 1526508898697595965) (-1) (SQLExecDirectW)")',)
  "detect unicode returns: %r" % de)
(3,)
```

`~/.odbc.ini`:
```
[EXA_TEST]:
DRIVER=/FILEPATH/libexaodbc-io352fw.dylib
EXAHOST=localhost:8563
EXASCHEMA=PUBLIC
EXAUID=USERNAME
EXAPWD=PASSWORD
```

How to solve this unicode issue without having to use try-except?

Thanks!

**Comment by expobrain** [comment]
Looks like Exasol's ODBC drivers don't like unicode strings, try to convert your SQL statements to ASCII before executing it

**Comment by BY-jk** [comment]
@reinholdsson - this is a behavior I have not observed so far. However, we test and run the dialect on Ubuntu/Debian. So Mac with some unixodbc port is not the environment we observe often.
I can't give you any concrete hint right now. What puzzles me is, that upon the second attempt everything is fine.
Can you give a bit more information on your setup:
* Python version
* Exasol Version (I assume it is EXASolo running in a VM)
* unixodbc version (installed via homebrew? how?)

**Comment by reinholdsson** [comment]
Thanks for the quick response. I'm running with the following setup:

- Python 2.7.11 |Anaconda 2.2.0 (x86_64)| (default, Dec  6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
- EXASolution 5.0.12 (running at another server with ssh, port-forwarding)
- unixODBC 2.3.2 (I think it was installed with `brew install unixodbc`, but not completely sure as it was a while ago)

Hope it helps. At the moment, I'm just trying it out on a Mac and will actually run the scripts on a ubuntu/centos machine later on. But, it would be great if it's possible to find a solution.

**Comment by expobrain** [comment]
This snippet should work:

```
import pyodbc

conn = pyodbc.connect('DSN=EXA_TEST')
sql = "select 3"
res = conn.execute(sql).fetchall()
print(res)
```

If it works try again but change the tipe of `sql` from `str` to `unicode` by prefixing the literal with `u`:

```
sql =u"select 3"
```

If with this modification you get a traceback like the one you posted above, it's a know bug.

The Exasol ODBC driver doesn't support unicode strings, a ticket is open on their support page https://www.exasol.com/support/browse/EXA-10027 (you need an account to see it); in the meanwhile I solved by disabling the unicode support in `sqlalchemy-exasol` (see https://github.com/expobrain/sqlalchemy_exasol/commit/2f408aa9c0998dbd3d19b1a1a3fc69c2a24acc0a)

**Comment by reinholdsson** [comment]
@expobrain great, thanks! https://github.com/expobrain/sqlalchemy_exasol/commit/2f408aa9c0998dbd3d19b1a1a3fc69c2a24acc0a solved it for me :)
